import Head from 'next/head';
import Link from 'next/link';

import { Button } from '@/ui/button';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta content='Generated by create next app' name='description' />
        <meta content='width=device-width, initial-scale=1' name='viewport' />
        <link href='/favicon.ico' rel='icon' />
      </Head>
      <main className='flex min-h-[100vh] items-center justify-center'>
        <Link href='/start'>
          <Button size='xs'>СТАРТ</Button>
        </Link>
      </main>
    </>
  );
}
